version: '3.4'

services:
  catalogdb:
    image: postgres
    
  basketdb:
    image: postgres
    
  distributedcache:
    image: redis
  
  orderdb:
    image: mcr.microsoft.com/azure-sql-edge
  
  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
  
  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
